package top.yukonga.mishka.custom.forms

// 本文件由 tools/forms/gen_specs.py 从参考实现的字段表生成，请勿手改。
// 数据源：tools/forms/fields.json（extract_fields.mjs 从 mihomo_box 的 WebUI 求值得到）。

enum class FormFieldType {
    TEXT, BOOL, NUMBER, SELECT, LIST, NUMLIST, USERLIST, TEXTAREA, MAPTEXT, MAPLIST,
    DNSLIST, APPLIST, HEADERS, FAKEIPRULE, RULESETPICK, CHECKBOX, PASSWORD, FILE, BUTTON,
}

data class FormOption(val value: String, val label: String)

data class FormField(
    val path: String,
    val label: String,
    val type: FormFieldType,
    val options: List<FormOption> = emptyList(),
    val optionsDynamic: String? = null,
    val desc: String? = null,
    val placeholder: String? = null,
    val hint: String? = null,
    val tag: String? = null,
    val tagWarn: Boolean = false,
    val default: Boolean? = null,
    val optional: Boolean = false,
    val allowEmpty: Boolean = false,
    val asSwitch: Boolean = false,
    val restartOnSave: Boolean = false,
    val boolKind: String? = null,
    val boolAs: String? = null,
    val tri: Boolean = false,
    val keyPlaceholder: String? = null,
    val dnsIpOnly: Boolean = false,
    val dns: Boolean = false,
) : FormRow

sealed interface FormRow
data class FormCustomRow(val kind: String) : FormRow

data class FormSection(val title: String, val fields: List<FormRow>)


/** 全局配置（对应参考实现 pages-config.js:137） */
val GENERAL_SECTIONS: List<FormSection> = listOf(
    FormSection("基础", listOf(
        FormField(
            path = "mode",
            label = "运行模式",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("rule", "规则"), FormOption("global", "全局"), FormOption("direct", "直连")),
            desc = "内核启动时的默认模式；主页上的模式切换只走外部面板 API，不会改动这里",
            optional = true,
            allowEmpty = true,
        ),
        FormField(
            path = "log-level",
            label = "日志等级",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("silent", "silent"), FormOption("error", "error"), FormOption("warning", "warning"), FormOption("info", "info"), FormOption("debug", "debug")),
            desc = "内核默认 info",
            optional = true,
            allowEmpty = true,
        ),
        FormField(
            path = "ipv6",
            label = "IPv6 总开关",
            type = FormFieldType.BOOL,
            desc = "内核默认开启；关闭则阻断所有 IPv6 连接及 AAAA 记录",
            default = true,
            optional = true,
        ),
        FormField(
            path = "unified-delay",
            label = "统一延迟",
            type = FormFieldType.BOOL,
            desc = "去除握手等额外延迟，更换延迟计算方式",
            optional = true,
        ),
        FormField(
            path = "tcp-concurrent",
            label = "TCP 并发",
            type = FormFieldType.BOOL,
            desc = "并发连接所有 IP，使用最快握手",
            optional = true,
        ),
        FormField(
            path = "allow-lan",
            label = "允许局域网连接",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "bind-address",
            label = "绑定地址",
            type = FormFieldType.TEXT,
            placeholder = "仅 allow-lan 为真时生效",
            optional = true,
        ),
        FormField(
            path = "interface-name",
            label = "出口网卡",
            type = FormFieldType.TEXT,
            placeholder = "如 wlan0",
            optional = true,
        ),
        FormField(
            path = "global-client-fingerprint",
            label = "全局指纹(旧内核)",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("chrome", "chrome"), FormOption("firefox", "firefox"), FormOption("safari", "safari"), FormOption("ios", "ios"), FormOption("android", "android"), FormOption("edge", "edge"), FormOption("random", "random")),
            tag = "新版本已移除",
            tagWarn = true,
            allowEmpty = true,
        ),
        FormField(
            path = "find-process-mode",
            label = "进程匹配模式",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("always", "always 总是匹配"), FormOption("strict", "strict 自动判断"), FormOption("off", "off 不匹配")),
            allowEmpty = true,
        ),
        FormField(
            path = "routing-mark",
            label = "路由标记 routing-mark",
            type = FormFieldType.NUMBER,
            optional = true,
        ),
        FormField(
            path = "global-ua",
            label = "全局 User-Agent",
            type = FormFieldType.TEXT,
            placeholder = "如 clash.meta",
            optional = true,
        ),
    )),
    FormSection("局域网访问控制", listOf(
        FormField(
            path = "authentication",
            label = "认证用户(用户:密码)",
            type = FormFieldType.LIST,
            hint = "user:password",
            optional = true,
        ),
        FormField(
            path = "skip-auth-prefixes",
            label = "跳过认证的 IP 段",
            type = FormFieldType.LIST,
            hint = "如 127.0.0.1/8",
            optional = true,
        ),
        FormField(
            path = "lan-allowed-ips",
            label = "允许接入的 IP 段",
            type = FormFieldType.LIST,
            hint = "如 0.0.0.0/0",
            optional = true,
        ),
        FormField(
            path = "lan-disallowed-ips",
            label = "禁止接入的 IP 段",
            type = FormFieldType.LIST,
            hint = "黑名单优先于白名单",
            optional = true,
        ),
    )),
    FormSection("外部控制 / API", listOf(
        FormField(
            path = "external-controller",
            label = "API 监听地址",
            type = FormFieldType.TEXT,
            placeholder = "127.0.0.1:9090",
            desc = "改地址后需重启内核",
            optional = true,
        ),
        FormField(
            path = "secret",
            label = "API 密钥",
            type = FormFieldType.TEXT,
            optional = true,
        ),
        FormField(
            path = "external-ui",
            label = "面板路径",
            type = FormFieldType.TEXT,
            placeholder = "如 ui（相对=工作目录下）",
            desc = "外部面板静态文件目录",
            optional = true,
        ),
        FormField(
            path = "external-ui-name",
            label = "面板目录名（URL 路径）",
            type = FormFieldType.TEXT,
            placeholder = "ui",
            desc = "访问路径名，空则直接用 external-ui",
            optional = true,
        ),
        FormField(
            path = "external-ui-url",
            label = "面板下载地址",
            type = FormFieldType.TEXT,
            desc = "无本地面板时自动下载。手机建议用无字体版（gh-pages-no-fonts.zip，1.4MB，走系统字体）：带字体版有 6MB+ 中文字形，首屏更慢、滚动更容易卡",
            optional = true,
        ),
        FormField(
            path = "external-controller-tls",
            label = "API TLS 监听地址",
            type = FormFieldType.TEXT,
            placeholder = "127.0.0.1:9443",
            optional = true,
        ),
        FormField(
            path = "external-controller-unix",
            label = "API Unix Socket",
            type = FormFieldType.TEXT,
            placeholder = "/tmp/mihomo.sock",
            optional = true,
        ),
        FormField(
            path = "external-controller-pipe",
            label = "API 命名管道",
            type = FormFieldType.TEXT,
            placeholder = "\\\\.\\pipe\\mihomo（Windows）",
            optional = true,
        ),
        FormField(
            path = "external-doh-server",
            label = "DoH 服务路径",
            type = FormFieldType.TEXT,
            placeholder = "如 /dns-query",
            optional = true,
        ),
        FormField(
            path = "external-controller-cors.allow-origins",
            label = "CORS 允许来源",
            type = FormFieldType.LIST,
            hint = "如 * 或 http://127.0.0.1",
            optional = true,
        ),
        FormField(
            path = "external-controller-cors.allow-private-network",
            label = "CORS 允许私有网络",
            type = FormFieldType.BOOL,
            optional = true,
        ),
    )),
    FormSection("Geo 数据", listOf(
        FormField(
            path = "geox-url.geoip",
            label = "GeoIP 下载地址",
            type = FormFieldType.TEXT,
            optional = true,
        ),
        FormField(
            path = "geox-url.geosite",
            label = "GeoSite 下载地址",
            type = FormFieldType.TEXT,
            optional = true,
        ),
        FormField(
            path = "geox-url.mmdb",
            label = "GeoIP MMDB 下载地址",
            type = FormFieldType.TEXT,
            optional = true,
        ),
        FormField(
            path = "geox-url.asn",
            label = "ASN 数据库地址",
            type = FormFieldType.TEXT,
            optional = true,
        ),
        FormField(
            path = "geo-auto-update",
            label = "Geo 数据自动更新",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "geo-update-interval",
            label = "更新间隔(小时)",
            type = FormFieldType.NUMBER,
            optional = true,
        ),
        FormField(
            path = "geosite-matcher",
            label = "GeoSite 匹配器",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("succinct", "succinct(默认)"), FormOption("mph", "mph(hybrid)")),
            allowEmpty = true,
        ),
    )),
    FormSection("杂项", listOf(
        FormField(
            path = "profile.store-selected",
            label = "记住节点选择",
            type = FormFieldType.BOOL,
            desc = "内核默认开启",
            default = true,
            optional = true,
            asSwitch = true,
        ),
        FormField(
            path = "profile.store-fake-ip",
            label = "持久化 fake-ip",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "keep-alive-interval",
            label = "TCP 保活探测间隔(秒)",
            type = FormFieldType.NUMBER,
            placeholder = "15",
            optional = true,
        ),
        FormField(
            path = "keep-alive-idle",
            label = "TCP 保活空闲时间(秒)",
            type = FormFieldType.NUMBER,
            placeholder = "600",
            optional = true,
        ),
        FormField(
            path = "disable-keep-alive",
            label = "禁用 TCP 保活",
            type = FormFieldType.BOOL,
            optional = true,
        ),
    )),
    FormSection("Smart 内核专属（LightGBM 模型）", listOf(
        FormField(
            path = "lgbm-auto-update",
            label = "模型自动更新",
            type = FormFieldType.BOOL,
            desc = "默认关闭",
            optional = true,
        ),
        FormField(
            path = "lgbm-update-interval",
            label = "更新间隔(小时)",
            type = FormFieldType.NUMBER,
            placeholder = "72",
            optional = true,
        ),
        FormField(
            path = "lgbm-url",
            label = "模型下载地址",
            type = FormFieldType.TEXT,
            placeholder = "模型 bin 文件 URL",
            optional = true,
        ),
        FormField(
            path = "profile.smart-collector-size",
            label = "采样数据大小 (MB)",
            type = FormFieldType.NUMBER,
            placeholder = "100",
            desc = "Smart 数据采集缓存大小",
            optional = true,
        ),
    )),
)

/** DNS（对应参考实现 pages-config.js:196） */
val DNS_SECTIONS: List<FormSection> = listOf(
    FormSection("基础", listOf(
        FormField(
            path = "dns.enable",
            label = "启用内置 DNS",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "dns.cache-algorithm",
            label = "缓存算法",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("arc", "arc"), FormOption("lru", "lru")),
            allowEmpty = true,
        ),
        FormField(
            path = "dns.prefer-h3",
            label = "优先 HTTP/3 DoH",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "dns.use-hosts",
            label = "使用 hosts",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("True", "开启"), FormOption("False", "关闭")),
            desc = "回应配置中的 hosts 映射；内核默认开启",
            optional = true,
            allowEmpty = true,
            boolKind = "True",
        ),
        FormField(
            path = "dns.use-system-hosts",
            label = "使用系统 hosts",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("True", "开启"), FormOption("False", "关闭")),
            desc = "查询系统 hosts；内核默认开启",
            optional = true,
            allowEmpty = true,
            boolKind = "True",
        ),
        FormField(
            path = "dns.respect-rules",
            label = "按规则分流解析",
            type = FormFieldType.BOOL,
            desc = "代理规则使用对应上游解析",
            optional = true,
        ),
        FormField(
            path = "dns.listen",
            label = "监听地址",
            type = FormFieldType.TEXT,
            placeholder = "0.0.0.0:7874",
            desc = "内核 DNS 服务器监听",
            optional = true,
        ),
        FormField(
            path = "dns.ipv6",
            label = "解析 IPv6 (AAAA)",
            type = FormFieldType.BOOL,
            optional = true,
        ),
    )),
    FormSection("增强模式 / fake-ip", listOf(
        FormField(
            path = "dns.enhanced-mode",
            label = "增强模式",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("normal", "normal"), FormOption("fake-ip", "fake-ip"), FormOption("redir-host", "redir-host")),
            desc = "fake-ip=虚拟 IP，加速且便于按域名分流；redir-host=返回真实 IP 并记录域名映射",
            allowEmpty = true,
        ),
        FormField(
            path = "dns.fake-ip-range",
            label = "fake-ip 地址池",
            type = FormFieldType.TEXT,
            placeholder = "198.18.0.1/16",
            desc = "fake-ip 模式的 IPv4 池，默认 198.18.0.1/16",
            optional = true,
        ),
        FormField(
            path = "dns.fake-ip-range6",
            label = "fake-ip v6 地址池",
            type = FormFieldType.TEXT,
            placeholder = "fd00::/108",
            desc = "可选，未设则不分配 v6 fake-ip",
            optional = true,
        ),
        FormField(
            path = "dns.fake-ip-filter-mode",
            label = "过滤模式",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("blacklist", "blacklist 黑名单"), FormOption("whitelist", "whitelist 白名单"), FormOption("rule", "rule 规则")),
            desc = "blacklist=命中走 real-ip；whitelist=仅命中走 fake-ip；rule=按规则逐条匹配 fake-ip/real-ip（与路由规则一致）",
            allowEmpty = true,
        ),
        FormField(
            path = "dns.fake-ip-filter",
            label = "fake-ip 过滤",
            type = FormFieldType.FAKEIPRULE,
            desc = "按 fake-ip-filter-mode 自动切换：rule 时为结构化规则表（逐条 fake-ip/real-ip，拖动排序，自上而下匹配），blacklist/whitelist 时为域名列表（*.lan / geosite:cn 等）",
            optional = true,
        ),
        FormField(
            path = "dns.fake-ip-ttl",
            label = "fake-ip TTL",
            type = FormFieldType.NUMBER,
            placeholder = "1",
            desc = "fake-ip 响应的 TTL（秒），内核默认 1",
            optional = true,
        ),
    )),
    FormSection("上游服务器", listOf(
        FormField(
            path = "dns.default-nameserver",
            label = "默认 DNS(解析上游)",
            type = FormFieldType.DNSLIST,
            desc = "引导 DNS：解析下方各服务器域名用，必须为 IP（可为加密 DNS）",
            optional = true,
            dnsIpOnly = true,
        ),
        FormField(
            path = "dns.nameserver",
            label = "主 DNS 服务器",
            type = FormFieldType.DNSLIST,
            optional = true,
        ),
        FormField(
            path = "dns.fallback",
            label = "fallback（已弃用）",
            type = FormFieldType.DNSLIST,
            desc = "旧版字段，Alpha 内核已弃用",
            tag = "弃用",
            tagWarn = true,
            optional = true,
        ),
        FormField(
            path = "dns.proxy-server-nameserver",
            label = "代理服务器解析 DNS",
            type = FormFieldType.DNSLIST,
            desc = "仅用于解析代理节点的域名，建议国内直连 DNS；不填则遵循 nameserver-policy/nameserver/fallback",
            optional = true,
        ),
        FormField(
            path = "dns.direct-nameserver",
            label = "直连规则 DNS",
            type = FormFieldType.DNSLIST,
            desc = "direct 出口域名解析用，配合 respect-rules 使用",
            optional = true,
        ),
        FormField(
            path = "dns.direct-nameserver-follow-policy",
            label = "直连 DNS 遵循策略",
            type = FormFieldType.BOOL,
            desc = "direct-nameserver 是否遵循 nameserver-policy，内核默认否；仅「直连规则 DNS」非空时生效",
            optional = true,
        ),
    )),
    FormSection("按域名分流解析", listOf(
        FormField(
            path = "dns.nameserver-policy",
            label = "nameserver-policy",
            type = FormFieldType.MAPLIST,
            desc = "域名/geosite → 专用 DNS 列表",
            optional = true,
            dns = true,
        ),
        FormField(
            path = "dns.proxy-server-nameserver-policy",
            label = "proxy-server-nameserver-policy",
            type = FormFieldType.MAPLIST,
            desc = "格式同 nameserver-policy，仅用于代理节点的域名解析；当且仅当「代理服务器解析 DNS」非空时生效",
            optional = true,
            keyPlaceholder = "节点域名，如 www.yournode.com 或 geosite:cn",
            dns = true,
        ),
    )),
    FormSection("hosts 自定义", listOf(
        FormField(
            path = "hosts",
            label = "hosts 自定义",
            type = FormFieldType.MAPLIST,
            desc = "键=域名（支持 *. 通配），值=IP，多个逗号分隔；类似 /etc/hosts",
            optional = true,
        ),
    )),
)

/** 域名嗅探（对应参考实现 pages-config.js:993） */
val SNIFF_SECTIONS: List<FormSection> = listOf(
    FormSection("", listOf(
    )),
    FormSection("基础", listOf(
        FormField(
            path = "sniffer.enable",
            label = "启用嗅探",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "sniffer.force-dns-mapping",
            label = "强制 DNS 映射",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("True", "开启"), FormOption("False", "关闭")),
            desc = "内核默认开启；对解析后 IP 的连接映射回域名再匹配规则",
            optional = true,
            allowEmpty = true,
            boolKind = "True",
        ),
        FormField(
            path = "sniffer.parse-pure-ip",
            label = "解析纯 IP 请求",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("True", "开启"), FormOption("False", "关闭")),
            desc = "内核默认开启；目标是纯 IP 的连接也进行嗅探",
            optional = true,
            allowEmpty = true,
            boolKind = "True",
        ),
        FormField(
            path = "sniffer.override-destination",
            label = "覆盖目标地址",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("True", "开启"), FormOption("False", "关闭")),
            desc = "内核默认开启；用嗅探出的域名覆盖连接的目标 IP",
            optional = true,
            allowEmpty = true,
            boolKind = "True",
        ),
    )),
    FormSection("协议端口与覆盖", listOf(
        FormField(
            path = "sniffer.sniff.HTTP.ports",
            label = "HTTP 监听端口",
            type = FormFieldType.NUMLIST,
            hint = "如 80, 8080",
            optional = true,
        ),
        FormField(
            path = "sniffer.sniff.HTTP.override-destination",
            label = "HTTP 覆盖目标地址",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "sniffer.sniff.TLS.ports",
            label = "TLS 监听端口",
            type = FormFieldType.NUMLIST,
            hint = "如 443, 8443",
            optional = true,
        ),
        FormField(
            path = "sniffer.sniff.TLS.override-destination",
            label = "TLS 覆盖目标地址",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "sniffer.sniff.QUIC.ports",
            label = "QUIC 监听端口",
            type = FormFieldType.NUMLIST,
            hint = "如 443",
            optional = true,
        ),
        FormField(
            path = "sniffer.sniff.QUIC.override-destination",
            label = "QUIC 覆盖目标地址",
            type = FormFieldType.BOOL,
            optional = true,
        ),
    )),
    FormSection("嗅探名单", listOf(
        FormField(
            path = "sniffer.force-domain",
            label = "强制嗅探的域名",
            type = FormFieldType.LIST,
            hint = "如 +.v2ex.com",
            optional = true,
        ),
        FormField(
            path = "sniffer.skip-domain",
            label = "跳过嗅探的域名",
            type = FormFieldType.LIST,
            hint = "如 Mijia Cloud / +.apple.com",
            optional = true,
        ),
        FormField(
            path = "sniffer.skip-src-address",
            label = "跳过来源地址段",
            type = FormFieldType.LIST,
            hint = "CIDR",
            optional = true,
        ),
        FormField(
            path = "sniffer.skip-dst-address",
            label = "跳过目标地址段",
            type = FormFieldType.LIST,
            hint = "CIDR",
            optional = true,
        ),
    )),
)

/** 入站·端口（对应参考实现 pages-config.js:233） */
val INBOUND_PORTS: List<FormSection> = listOf(
    FormSection("端口（0 或留空 = 禁用该项）", listOf(
        FormField(
            path = "port",
            label = "HTTP 代理端口",
            type = FormFieldType.NUMBER,
            optional = true,
        ),
        FormField(
            path = "socks-port",
            label = "SOCKS5 代理端口",
            type = FormFieldType.NUMBER,
            optional = true,
        ),
        FormField(
            path = "mixed-port",
            label = "HTTP+SOCKS 混合端口",
            type = FormFieldType.NUMBER,
            optional = true,
        ),
        FormField(
            path = "redir-port",
            label = "Redir 透明代理端口",
            type = FormFieldType.NUMBER,
            optional = true,
        ),
        FormField(
            path = "tproxy-port",
            label = "TProxy 端口 (TCP/UDP)",
            type = FormFieldType.NUMBER,
            optional = true,
        ),
    )),
)

/** 入站·TUN（对应参考实现 pages-config.js:269） */
val TUN_SECTIONS: List<FormSection> = listOf(
    FormSection("基础", listOf(
        FormField(
            path = "tun.enable",
            label = "启用 TUN",
            type = FormFieldType.BOOL,
            desc = "开启时自动把 eBPF 入站的 local.enable / shared.enable 置为 false（参数原样保留，改回 true 即恢复）",
            optional = true,
            restartOnSave = true,
        ),
        FormField(
            path = "tun.stack",
            label = "协议栈",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("system", "system（系统栈·占用低）"), FormOption("gvisor", "gvisor（默认）"), FormOption("mixed", "mixed（官方建议）"), FormOption("mips", "mips（自研栈·新内核）")),
            desc = "留空 = 内核默认 gvisor。system=系统协议栈，更稳定全面、占用相对更低；gvisor=用户态实现，隔离性更好；mixed=TCP 走 system、UDP 走 gvisor，无使用问题时官方建议用它；mips=mihomo 自研 IP 协议栈，需内核 ≥ v1.19.31，旧内核会启动失败",
            allowEmpty = true,
        ),
        FormField(
            path = "tun.device",
            label = "虚拟网卡名",
            type = FormFieldType.TEXT,
            placeholder = "默认 Meta",
            optional = true,
        ),
        FormField(
            path = "tun.mtu",
            label = "MTU",
            type = FormFieldType.NUMBER,
            placeholder = "9000",
            optional = true,
        ),
        FormField(
            path = "tun.gso",
            label = "GSO 分段卸载",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "tun.gso-max-size",
            label = "GSO 最大包长",
            type = FormFieldType.NUMBER,
            optional = true,
        ),
    )),
    FormSection("路由", listOf(
        FormField(
            path = "tun.auto-route",
            label = "自动配置路由表",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "tun.auto-redirect",
            label = "自动配置 iptables 重定向",
            type = FormFieldType.BOOL,
            desc = "本机 TCP 快速重定向（Android 上 sing-tun 仅装 OUTPUT 链，不作用于转发流量）；热点共享的转发放行由模块自动完成，不依赖此项",
            optional = true,
        ),
        FormField(
            path = "tun.auto-detect-interface",
            label = "自动识别出口网卡",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "tun.strict-route",
            label = "严格路由",
            type = FormFieldType.BOOL,
            desc = "防止泄漏，但局域网不可达",
            optional = true,
        ),
        FormField(
            path = "tun.disable-icmp-forwarding",
            label = "禁用 ICMP 转发",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "tun.route-address",
            label = "自定义路由地址集",
            type = FormFieldType.LIST,
            hint = "如 0.0.0.0/1",
            optional = true,
        ),
        FormField(
            path = "tun.route-address-set",
            label = "路由规则集(包含)",
            type = FormFieldType.LIST,
            hint = "rule-set 名称",
            optional = true,
        ),
        FormField(
            path = "tun.route-exclude-address-set",
            label = "路由规则集(排除)",
            type = FormFieldType.LIST,
            optional = true,
        ),
        FormField(
            path = "tun.endpoint-independent-nat",
            label = "独立于端点的 NAT (EIM)",
            type = FormFieldType.BOOL,
            optional = true,
        ),
        FormField(
            path = "tun.dns-hijack",
            label = "DNS 劫持地址",
            type = FormFieldType.LIST,
            hint = "如 any:53",
            optional = true,
        ),
        FormField(
            path = "tun.udp-timeout",
            label = "UDP NAT 超时(秒)",
            type = FormFieldType.NUMBER,
            optional = true,
        ),
    )),
    FormSection("范围过滤（需 auto-route）", listOf(
        FormField(
            path = "tun.include-android-user",
            label = "包含的安卓用户 ID",
            type = FormFieldType.NUMLIST,
            hint = "如 0、10",
            optional = true,
        ),
        FormField(
            path = "tun.include-package",
            label = "仅代理以下应用",
            type = FormFieldType.APPLIST,
            desc = "留空 = 全部应用；Tproxy 开启时同样生效（白名单，优先于排除名单）",
            optional = true,
        ),
        FormField(
            path = "tun.exclude-package",
            label = "排除以下应用",
            type = FormFieldType.APPLIST,
            desc = "被排除应用直连；Tproxy 开启时同样生效（黑名单）",
            optional = true,
        ),
        FormField(
            path = "tun.include-uid",
            label = "包含 UID",
            type = FormFieldType.NUMLIST,
            optional = true,
        ),
        FormField(
            path = "tun.exclude-uid",
            label = "排除 UID",
            type = FormFieldType.NUMLIST,
            optional = true,
        ),
        FormField(
            path = "tun.include-uid-range",
            label = "包含 UID 范围",
            type = FormFieldType.LIST,
            hint = "start:end，如 10000:19999",
            optional = true,
        ),
        FormField(
            path = "tun.exclude-uid-range",
            label = "排除 UID 范围",
            type = FormFieldType.LIST,
            optional = true,
        ),
        FormField(
            path = "tun.include-interface",
            label = "包含网卡",
            type = FormFieldType.LIST,
            optional = true,
        ),
        FormField(
            path = "tun.exclude-interface",
            label = "排除网卡",
            type = FormFieldType.LIST,
            optional = true,
        ),
        FormField(
            path = "tun.include-mac-address",
            label = "包含 MAC 地址",
            type = FormFieldType.LIST,
            hint = "AA:BB:CC:DD:EE:FF",
            optional = true,
        ),
        FormField(
            path = "tun.exclude-mac-address",
            label = "排除 MAC 地址",
            type = FormFieldType.LIST,
            optional = true,
        ),
    )),
)

/** 入站·eBPF（对应参考实现 pages-config.js:341） */
val EBPF_SECTIONS: List<FormSection> = listOf(
    FormSection("基础（listeners[].type=ebpf）", listOf(
        FormCustomRow("ebpf.master"),
        FormField(
            path = "name",
            label = "名称 name",
            type = FormFieldType.TEXT,
            optional = true,
        ),
        FormCustomRow("network"),
        FormField(
            path = "udp-timeout",
            label = "UDP 超时(秒)",
            type = FormFieldType.NUMBER,
            placeholder = "内核默认 300，最小 5",
            desc = "可热更新：单独改它不重建入站，已建立的会话与热点客户端不会被打断",
            optional = true,
        ),
        FormField(
            path = "tc-priority",
            label = "TC 优先级 tc-priority",
            type = FormFieldType.NUMBER,
            placeholder = "默认 1",
            desc = "默认 1：内核支持时经 TCX 挂载，否则 clsact；填其他值一律用 clsact 过滤器",
            optional = true,
        ),
        FormField(
            path = "bypass-rule-set",
            label = "绕行规则集",
            type = FormFieldType.RULESETPICK,
            desc = "从已添加的规则集（rule-providers）中选择，命中的 CIDR 在内核里直接绕行。仅 behavior: ipcidr 的规则集会生效，其余被跳过；规则集内容自行更新无需重启内核",
            optional = true,
        ),
        FormField(
            path = "bypass-tun-direct",
            label = "绕过项直达(配合TUN)",
            type = FormFieldType.BOOL,
            desc = "内核默认开启。被 bypass 的目标仍走路由表、会被 TUN auto-route 声称：开启=命中绕行的流量到达时直接直连，不经 TUN 规则匹配；关闭=只报告与 TUN 的重叠、不做处理（进 TUN 后没有直连规则可能黑洞）。仅规则模式生效；bypass-private-address 的路由排除不受此开关影响",
            optional = true,
            boolAs = "pick",
        ),
        FormCustomRow("fakeip-icmp"),
    )),
    FormSection("local 模式（cgroup 本机应用）", listOf(
        FormCustomRow("local.enable"),
        FormField(
            path = "local.data-plane",
            label = "数据面 data-plane",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("cgroup", "cgroup 挂载（默认）"), FormOption("tc", "tc egress + veth（内核 ≥5.7）")),
            desc = "cgroup=接管本机套接字；tc=默认网卡 egress 抓包（内核运行时探测可用性）",
            optional = true,
            allowEmpty = true,
        ),
        FormField(
            path = "local.cgroup-path",
            label = "cgroup 路径",
            type = FormFieldType.TEXT,
            placeholder = "留空自动探测，一般无需填写",
            desc = "仅 data-plane=cgroup 可填，且必须是 cgroup2 挂载内的绝对路径",
            optional = true,
        ),
        FormField(
            path = "local.dns-mode",
            label = "DNS 处理 dns-mode",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("hijack", "hijack 劫持（内核默认）"), FormOption("respect_policy", "respect_policy 先按策略"), FormOption("off", "off 不处理")),
            desc = "hijack=接管所有 53 端口流量；respect_policy=先按 UID/来源策略；off=不处理",
            optional = true,
            allowEmpty = true,
        ),
        FormField(
            path = "local.ipv6",
            label = "接管 IPv6",
            type = FormFieldType.BOOL,
            desc = "内核默认开启",
            optional = true,
            boolAs = "pick",
        ),
        FormField(
            path = "local.bypass-private-address",
            label = "绕过私有地址",
            type = FormFieldType.BOOL,
            desc = "内核默认开启。开启=私有网段（10/8、172.16/12、192.168/16、100.64/10、169.254/16、fc00::/7、fe80::/10）不接管直连；网关想把 LAN 流量看进连接列表就选「关」",
            optional = true,
            boolAs = "pick",
        ),
        FormField(
            path = "local.include-uid",
            label = "包含 UID",
            type = FormFieldType.NUMLIST,
            optional = true,
        ),
        FormField(
            path = "local.include-uid-range",
            label = "包含 UID 范围",
            type = FormFieldType.LIST,
            hint = "start:end",
            optional = true,
        ),
        FormField(
            path = "local.exclude-uid",
            label = "排除 UID",
            type = FormFieldType.NUMLIST,
            optional = true,
        ),
        FormField(
            path = "local.exclude-uid-range",
            label = "排除 UID 范围",
            type = FormFieldType.LIST,
            hint = "start:end",
            optional = true,
        ),
        FormField(
            path = "local.include-android-user",
            label = "包含安卓用户",
            type = FormFieldType.NUMLIST,
            hint = "如 0、10（多开/工作资料）",
            optional = true,
        ),
        FormField(
            path = "local.include-package",
            label = "仅代理以下应用",
            type = FormFieldType.APPLIST,
            optional = true,
        ),
        FormField(
            path = "local.exclude-package",
            label = "排除以下应用",
            type = FormFieldType.APPLIST,
            optional = true,
        ),
        FormField(
            path = "local.bypass-port",
            label = "绕过目标端口",
            type = FormFieldType.NUMLIST,
            desc = "发往这些目标端口的流量一律不接管（DNS 劫持仍按 dns-mode 处理）",
            hint = "如 22、3478",
            optional = true,
        ),
        FormField(
            path = "local.bypass-port-range",
            label = "绕过端口范围",
            type = FormFieldType.LIST,
            hint = "start:end，如 27000:27100",
            optional = true,
        ),
    )),
    FormSection("shared 模式（热点/共享网络 TC 转发）", listOf(
        FormCustomRow("shared.enable"),
        FormField(
            path = "shared.data-plane",
            label = "数据面 data-plane",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("packet_rewrite", "packet_rewrite 改写（默认）"), FormOption("socket_assign", "socket_assign sk_assign（内核 ≥5.7）")),
            desc = "packet_rewrite 需要以太网帧（MAC 名单也要）；raw-IP 链路（如部分 USB 网络共享）需 socket_assign",
            optional = true,
            allowEmpty = true,
        ),
        FormField(
            path = "shared.dns-mode",
            label = "DNS 处理 dns-mode",
            type = FormFieldType.SELECT,
            options = listOf(FormOption("hijack", "hijack 劫持（内核默认）"), FormOption("respect_policy", "respect_policy 先按策略"), FormOption("off", "off 不处理")),
            desc = "hijack=接管所有 53 端口流量；respect_policy=先按 UID/来源策略；off=不处理",
            optional = true,
            allowEmpty = true,
        ),
        FormField(
            path = "shared.interface",
            label = "下游接口",
            type = FormFieldType.LIST,
            desc = "shared / hybrid 下必填且不能是 lo；正作为默认上游的接口会被暂时跳过，回到下游角色后自动接管",
            hint = "如 wlan0、ap0、swlan0",
            optional = true,
        ),
        FormField(
            path = "shared.ipv6",
            label = "接管 IPv6",
            type = FormFieldType.BOOL,
            desc = "内核默认开启",
            optional = true,
            boolAs = "pick",
        ),
        FormField(
            path = "shared.bypass-private-address",
            label = "绕过私有地址",
            type = FormFieldType.BOOL,
            desc = "内核默认开启。开启=来自热点的私有网段目标不接管直连",
            optional = true,
            boolAs = "pick",
        ),
        FormField(
            path = "shared.include-source-cidr",
            label = "包含来源 CIDR",
            type = FormFieldType.LIST,
            hint = "如 192.168.43.0/24",
            optional = true,
        ),
        FormField(
            path = "shared.exclude-source-cidr",
            label = "排除来源 CIDR",
            type = FormFieldType.LIST,
            optional = true,
        ),
        FormField(
            path = "shared.include-mac-address",
            label = "包含 MAC",
            type = FormFieldType.LIST,
            hint = "aa:bb:cc:dd:ee:ff",
            optional = true,
        ),
        FormField(
            path = "shared.exclude-mac-address",
            label = "排除 MAC",
            type = FormFieldType.LIST,
            optional = true,
        ),
        FormField(
            path = "shared.bypass-port",
            label = "绕过目标端口",
            type = FormFieldType.NUMLIST,
            desc = "发往这些目标端口的下游流量一律不接管",
            hint = "如 22、3478",
            optional = true,
        ),
        FormField(
            path = "shared.bypass-port-range",
            label = "绕过端口范围",
            type = FormFieldType.LIST,
            hint = "start:end，如 27000:27100",
            optional = true,
        ),
    )),
)

/** NTP（对应参考实现 pages-config.js:243） */
val NTP_SECTIONS: List<FormSection> = listOf(
    FormSection("NTP 时间同步", listOf(
        FormField(
            path = "ntp.enable",
            label = "启用 NTP",
            type = FormFieldType.BOOL,
            desc = "TLS 握手对时间敏感",
            optional = true,
            boolAs = "pick",
        ),
        FormField(
            path = "ntp.server",
            label = "NTP 服务器",
            type = FormFieldType.TEXT,
            placeholder = "time.apple.com",
            optional = true,
        ),
        FormField(
            path = "ntp.port",
            label = "NTP 端口",
            type = FormFieldType.NUMBER,
            placeholder = "123",
            optional = true,
        ),
        FormField(
            path = "ntp.interval",
            label = "同步间隔(分钟)",
            type = FormFieldType.NUMBER,
            optional = true,
        ),
        FormField(
            path = "ntp.write-to-system",
            label = "同步后写入系统时间",
            type = FormFieldType.BOOL,
            tag = "需 root",
            tagWarn = true,
            optional = true,
            boolAs = "pick",
        ),
        FormField(
            path = "ntp.dialer-proxy",
            label = "NTP 出站代理 dialer-proxy",
            type = FormFieldType.SELECT,
            desc = "默认 DIRECT；强制 NTP 走指定出站",
            allowEmpty = true,
        ),
    )),
)

/** 实验性配置（对应参考实现 pages-config.js:255） */
val EXPERIMENTAL_SECTIONS: List<FormSection> = listOf(
    FormSection("", listOf(
    )),
    FormSection("QUIC / 拨号器", listOf(
        FormField(
            path = "experimental.quic-go-disable-gso",
            label = "禁用 QUIC GSO",
            type = FormFieldType.BOOL,
            desc = "打开 = 关闭 GSO 分段卸载加速",
            optional = true,
            tri = true,
        ),
        FormField(
            path = "experimental.quic-go-disable-ecn",
            label = "禁用 QUIC ECN",
            type = FormFieldType.BOOL,
            desc = "打开 = 关闭 QUIC 的 ECN 显式拥塞通知；部分网络设备会丢弃 ECN 标记包，QUIC 变慢/不通时可开启",
            default = true,
            optional = true,
        ),
        FormField(
            path = "experimental.dialer-ip4p-convert",
            label = "IP4P 地址转换",
            type = FormFieldType.BOOL,
            desc = "启用 IP4P 地址转换（natmap 域名访问）",
            optional = true,
            tri = true,
        ),
    )),
)
