org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.tooling.parallel=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.r8.gradual.support=true

kotlin.code.style=official
kotlin.mpp.applyDefaultHierarchyTemplate=false

mihomo.version=v1.19.31+
